### ISSUE TITLE
CircleCI Error: Cannot Set Host Name: Operation not permitted

### ISSUE THREAD

**Issue by james-luther** [fluidattacks/makes#1127]
I'm attempting to run makes in CircleCI and whenever I run makes it fails with the error:

`error: cannot set host name: Operation not permitted`

I've attempted using the nixos/nix container and the ghcr.io/fluidattacks/makes/amd64 container. 

Whenever I run a build such as:

`m github:fluidattacks/makes@main` 
or 
`m gitlab:fluidattacks/universe@trunk` 

The error mentioned above occurs. When I run this locally in docker everything works fine. The error only occurs within CircleCI. I found documentation recommending to set `sandbox = false` but this doesn't make a difference. 

My question is, could this be something that can be fixed within makes itself, the nix.conf or is it a CircleCI issue?

**Comment by dsalaza4** [comment]
Hi @james-luther,

Neither the container nor the CLI modify the host name AFAIK.

Can you provide more details about this error:

1. What Makes job you're running
2. Execution logs
3. Do other CI/CD jobs work properly when ran on your Circle CI?

**Comment by james-luther** [comment]
So, I figured out a way around this. It's not ideal but by using remote-docker within CircleCI everything completes successfully. 

The specific job is:
```
  fluidattacks:
    docker: 
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Setup Prerequisites
          command: |
            sudo apt update
            sudo apt -y install csvkit
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Verify Configuration
          command: |
            mv ~/project/.circleci/casa/config.yaml ~/project/config.yaml
      - run:
          name: Setup Fluidattacks
          command: |
            docker create -v /working-dir --name repo alpine:3.4 /bin/true
            docker cp /home/circleci/project repo:/working-dir
      - run:
          name: Run CASA SAST scan
          command: |
            docker run --volumes-from repo --name fluidattacks ghcr.io/fluidattacks/makes/amd64 m gitlab:fluidattacks/universe@trunk /skims scan project/config.yaml
```

I excluded the portions that use csvkit as they are not important.

By using the section:
```
- setup_remote_docker:
    version: 20.10.14
```

Everything completes as expected.
