### ISSUE TITLE
Github action don't output to file

### ISSUE THREAD

**Issue by prrvchr** [fluidattacks/makes#1189]
Hi,

I have a [Github action](https://github.com/prrvchr/OAuth2OOo/actions/workflows/fascan.yml) who scan my code with FluidAttacks but the [output file](https://github.com/prrvchr/OAuth2OOo/blob/master/Fluid-Attacks-Results.csv) is not updated at the end of the scan.

If I run the same job locally (without Github action but with this [bash script](https://github.com/prrvchr/OAuth2OOo/blob/master/Fluid-Attacks-Scan.sh)) the output file is updated locally...

Any idea?

**Comment by LuisPatino92** [comment]
Hello, your configuration seems fine. I cloned the current state of the repo and executed the scanner using your configuration file. All logs indicate that the scan targeted the specified files, and no vulnerabilities were detected.

I recommend checking the following:

- Ensure that the configuration used locally [`_fascan.yml`] is identical.
- Confirm that all changes made during the local scan are included in the commit.

If the problem persists, I encourage you to open an issue on Fluid Attacks' [GitLab](https://gitlab.com/fluidattacks/universe/-/issues), providing evidence of the output obtained locally and any other relevant information.

I'm closing this issue as it appears to be more related to Skims (the scanner) or GitHub Actions than to 'makes.'

**Comment by prrvchr** [comment]
Hi,
It seems to me that this must be linked to github actions since it works fine locally.
Maybe it's a permission issue on the repository and fluid attacks can't update the Fluid-Attacks-Results.csv file?

**Comment by prrvchr** [comment]
Ok I finally found the right syntax for the `.github/workflows/fascan.yml` file so that it is able to log the scan result in the file: `Fluid-Attacks Results.csv`

```
# .github/workflows/fascan.yml
name: Fluid Attacks Scan
on: [push, pull_request]
jobs:
  machineStandalone:
    name: machineStandalone job
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fluid-Attacks scan
        uses: docker://ghcr.io/fluidattacks/makes/amd64
        with:
          args: m gitlab:fluidattacks/universe@trunk /skims scan ./_fascan.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "prrvchr@gmail.com"
          git config --global user.name "prrvchr"
          git commit -am "Fluid-Attacks Results.csv commit"
          git push
```

It is necessary to adjust the email address and name accordingly.

@LuisPatino92 I think it would be good to put this info in your documentation because if we want to use **Fluid Attacks** with **GitHub actions**, updating the `Fluid-Attacks Results.csv` file cannot be done without this info.
