### ISSUE TITLE
Infer poetry python version env from toml file

### ISSUE THREAD

**Issue by blotero** [fluidattacks/makes#1280]
Python version environment is received as first argument in the makePythonLock` builtin as introduced in #1275. This is however redundant considering that poetry environment version should match the field in the `pyproject.toml` file:

```toml
[tool.poetry.dependencies]
python = <ENV VERSION>
```

It would be desirable to infer this field from the `pyproject.toml` file instead of being passed as an argument.
