### ISSUE TITLE
Problem - Key: namespace is required

### ISSUE THREAD

**Issue by BlackRoosie** [fluidattacks/makes#983]
I got a problem during executing command: 
 m gitlab:fluidattacks/universe@trunk /skims scan ~/.makes/cache/sources/gitlab-fluidattacks-universe-trunk/integrates/secrets/lint/config.yaml

`[WARNING] Function: __main__.cli_scan_wrapped, type: Key: namespace is required
Traceback (most recent call last):
  File "/nix/store/ns80wma6fhz5cdsd1zz1sz9xyv4kx670-skims/config/__init__.py", line 141, in load
    namespace=config.pop("namespace"),
KeyError: 'namespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ns80wma6fhz5cdsd1zz1sz9xyv4kx670-skims/utils/function.py", line 220, in wrapper
    return function(*args, **kwargs)
  File "/nix/store/ns80wma6fhz5cdsd1zz1sz9xyv4kx670-skims/cli/__init__.py", line 121, in cli_scan_wrapped
    success: bool = run(
  File "/nix/store/33z2zxmvnq9k4fmbqim6ffzhlgiwmxb6-skims-runtime/lib/python3.8/site-packages/aioextensions/__init__.py", line 292, in run
    return asyncio.run(coroutine, debug=debug)
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/ns80wma6fhz5cdsd1zz1sz9xyv4kx670-skims/core/scan.py", line 233, in main
    load(group, config)  # NOSONAR
  File "/nix/store/ns80wma6fhz5cdsd1zz1sz9xyv4kx670-skims/config/__init__.py", line 161, in load
    raise confuse.ConfigError(f"Key: {exc.args[0]} is required")
confuse.exceptions.ConfigError: Key: namespace is required

[INFO] Success: False`

Can you help me to solve it?

**Comment by drestrepom** [comment]
You must specify a namespace with any name
```yaml
language: EN
namespace: namespace
output:
  file_path: skims/test/outputs/lib_path.csv
  format: CSV
path:
  exclude:
    - glob(integrates/**/*)
  include:
    - skims/test/data/lib_path
  lib_path: true
  lib_root: false

```
https://gitlab.com/fluidattacks/universe/-/blob/6f37e27fa19521f993e4c18af330cfdb4e90b18e/skims/test/data/config/lib_path.yaml#L3
